# 베이스 이미지 설정
FROM python:3.10-bookworm

# 작업 디렉토리 설정
WORKDIR /app

# 호스트의 현재 디렉토리의 모든 파일을 컨테이너의 /app 폴더로 복사
COPY . /app

# 필요한 패키지 설치
RUN pip install -r requirements.txt

# 컨테이너 실행 시 실행할 명령 설정
CMD ["python", "main.py"]
